ALTER TABLE EMPLOYEE
DROP COLUMN dob;

ALTER TABLE works
DROP CONSTRAINT SYS_C007398;

ALTER TABLE manages
DROP CONSTRAINT SYS_C007400;

ALTER TABLE EMPLOYEE
DROP PRIMARY KEY;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EMPLOYEE_NAME, BRANCH_NAME);

ALTER TABLE EMPLOYEE
ADD UNIQUE (EMPLOYEE_NAME);

ALTER TABLE WORKS
ADD FOREIGN KEY(EMPLOYEE_NAME) REFERENCES EMPLOYEE(EMPLOYEE_NAME);

ALTER TABLE MANAGES
ADD FOREIGN KEY(EMPLOYEE_NAME) REFERENCES EMPLOYEE(EMPLOYEE_NAME);


clear screen

/*exp3*/

ALTER TABLE company
DROP PRIMARY KEY;

ALTER TABLE company
DROP COLUMN company_name;

ALTER TABLE company
ADD company_name varchar(30);

ALTER TABLE company
ADD PRIMARY KEY(company_name);

ALTER TABLE works
MODIFY company_name varchar(30);

ALTER TABLE employee
ADD (street varchar(20), city varchar(20));

UPDATE employee
SET street='GANDHI NAGAR', city='PANAT'
WHERE employee_name='SHIKHAR';

UPDATE employee
SET city='DUCKWORTH'
WHERE REGEXP_LIKE (employee_name, '(RUSH)|(SAMANTHA)');

